### ISSUE TITLE
Won't start on Ubuntu 24.04

### ISSUE THREAD

**Issue by vicesalles** [brick-a-brack/eagle-animation#108]
Hi there,

After installing via dpkg the program won't launch. I'm using Ubuntu 24.04.1. 

greetings

**Comment by vicesalles** [comment]
downloading the compressed files and running the @brick-a-brackeagle-animation file directly works.

**Comment by Maxou44** [comment]
When you use the dpkg, do you have an error ?

**Comment by vicesalles** [comment]
No, it goes quiet, smooth. No errors, no dependency messages, nothing. It looks like a succesfull installation. Sorry, no logs, nothing to share. Just won't start on clicking the icon

**Comment by Maxou44** [comment]
Is providing a rpm file can solve the issue?

**Comment by Maxou44** [comment]
The next version (2.9.x) will fix this issue 🙂
