### ISSUE TITLE
Provide an `rpm`

### ISSUE THREAD

**Issue by stefanfoulis** [brick-a-brack/eagle-animation#109]
Provide an `rpm` as part of the release.
(In my case for Fedora)

Maybe as a intermediate solution: provide documentation on how to run eagle-animation from the generic linux release.

**Comment by Maxou44** [comment]
Thanks for your feedback, I will try to bundle it as rpm file in the future 👌

You can manually build it using NodeJS using the following commands :
- npm i --force
- npm run build:linux 

The web version is also available in https://app.eagle-animation.com

**Comment by stefanfoulis** [comment]
On second thought about providing an `rpm` release.... Maybe it would make more sense to provide a `flatpak` or `appimage` :thinking: . Then we'd reach more different linux distros with one additional package type.

**Comment by Maxou44** [comment]
The next version (2.9.x) will be bundled as rpm, AppImage and flatpak. The app binary have been renamed from "@brick-a-brickeagle-animation" to "eagle-animation".

**Comment by stefanfoulis** [comment]
I briefly tried out the new AppImage in 2.9.0 today (on Fedora 41 in Gnome) and everything seems to work :+1:

**Comment by Maxou44** [comment]
Awesome! Thanks for the feedback! 🙂👌
