### ISSUE TITLE
Upgrade to DND-Kit from `react-sortable-hoc`

### ISSUE THREAD

**Issue by Swivelgames** [brick-a-brack/eagle-animation#35]
I was pulling this down and I couldn't help but notice the need for `--force` during the install. It looks like the culprit is `react-sortable-hoc`, which has been deprecated for some time now. It might be useful to upgrade to [dnd-kit](https://github.com/clauderic/dnd-kit) instead, which is the successor to react-sortable-hoc.

Thoughts?

**Comment by Maxou44** [comment]
Updated on dev branch, will be released in Eagle Animation 2.5.0 😉
