### ISSUE TITLE
Does it support running on the web?

### ISSUE THREAD

**Issue by tanies** [brick-a-brack/eagle-animation#46]
Hello, I am preparing to use your project to learn the code. I followed the instructions to execute npm i -- force, npm start, and open it in the browser using the localhost: 8282 port. However, the page prompts that window.IPC is undefined in src/renderer/index.js, so I am not sure if the project does not support it, or if there is a problem with my startup or node environment

**Comment by Maxou44** [comment]
The project is split in 2 parts : 
- A web app for the interface and provide user control
- The Electron (backend) part that create files and allow the app to do operations on the user drive

At the moment, both are required, npm start should open a new window and it should be usable, you should use this window, it's not possible to open it in a classic web browser.

In the future, we plan to.make a full web/mobile app that allow users to use the app using a classic web browser 😊

**Comment by Maxou44** [comment]
📣 Eagle Animation can now be used from any browser, although some features are a bit more limited.

➡️ The announcement will be made when version 2.5.0 will be released, but you can already access it on the `dev` branch or on https://app.eagle-animation.com/ 

I close the issue 😉
